### ISSUE TITLE
Setting up conda environment

### ISSUE THREAD

**Issue by swanss** [dauparas/ProteinMPNN#10]
Hi Justin! I just looked around the repo and couldn't find a .yaml file for setting up the conda environment (`mlfold` in the examples). Did I miss it, or does that still need to be added?

Very excited to try out some sequence design with ProteinMPNN!

**Comment by jadolfbr** [comment]
Agreed.  All the examples have mlfold in them and a .yaml file would be useful here...

**Comment by dauparas** [comment]
Hey! I have added a very short description on the conda environment setup in the README file. 

All examples are using my mlfold environment which has many unnecessary dependencies for ProteinMPNN. To run the code in this repo you just need pytorch! Good luck!
