### ISSUE TITLE
Weights without adding noise during training or training code

### ISSUE THREAD

**Issue by YifanDengWHU** [dauparas/ProteinMPNN#13]
Hi, thanks for the great work!
I have been trying to reproduce the results reported in the ProteinMPNN paper. While I can only obtain test ppl ~ 5.7, which is a little bigger than the result in the paper 4.74/5.25 w/ and w/o adding noise during training. I also loaded the v_48_002.pt weight and I can obtain test ppl 5.29, which is almost the same as the result reported in the paper.
So I wonder whether you can release the weights which doesn't add noise during training? Or whether you can share your training code? Thank you so much!

**Comment by dauparas** [comment]
Hey! I will upload training scripts for the results in the Table 2 using CATH training data. These models are different from the ProteinMPNN models which were trained on PDB biounits.
