### ISSUE TITLE
Getting last layer representations of the encoder and decoder?

### ISSUE THREAD

**Issue by johnnytam100** [dauparas/ProteinMPNN#14]
Hi @dauparas ! 
Would you mind telling us which variables are the last layer representations of the encoder and decoder?
I want to output those representations.
Thank you!

**Comment by dauparas** [comment]
Hey! 

Sure, the encoder last activations are https://github.com/dauparas/ProteinMPNN/blob/main/protein_mpnn_utils.py#L1048
after this line:

h_V - [batch, protein length, 128] - node embedding
h_E - [batch, protein length, 48, 128] - edge embedding

The decoder last activations are:
https://github.com/dauparas/ProteinMPNN/blob/main/protein_mpnn_utils.py#L1075
after this line:
h_V - [batch, protein length, 128] - node embedding
