### ISSUE TITLE
Adding support for residues to design

### ISSUE THREAD

**Issue by gezmi** [dauparas/ProteinMPNN#17]
Hi,

wonderful tool, however it is a bit hard to use when trying to design an interface. When I have only a couple of AAs for design and a lots of fixed ones, it is tedious to list all the fixed ones. Is it possible to include a script to which we only provide a list of enabled positions?
Thank you!

**Comment by dauparas** [comment]
Hello,

Yes, check this example: 
https://github.com/dauparas/ProteinMPNN/blob/main/examples/submit_example_4_non_fixed.sh

**Comment by gezmi** [comment]
Thank you very much!!!
