### ISSUE TITLE
What does scoring depend on?

### ISSUE THREAD

**Issue by gezmi** [dauparas/ProteinMPNN#19]
Hi,

I am trying to score structures, however I am not sure why the network does not give the same score with the same input structure, noise, temperature and seed.

e.g
```
>protein_unrelaxed_rank_1_model_5, score=1.5509, global_score=1.5065, fixed_chains=['B', 'C', 'D'], designed_chains=['E'], CA_model_name=v_48_020, git_hash=905b0081f3aa3404d7ac22174bc25710f9995ff8, seed=565

>protein_unrelaxed_rank_1_model_5, score=1.5227, global_score=1.5124, fixed_chains=['B', 'C', 'D'], designed_chains=['E'], CA_model_name=v_48_020, git_hash=905b0081f3aa3404d7ac22174bc25710f9995ff8, seed=565
```

These two runs was submitted on the exact same structure (coming from AF2), fixed positions, noise, temperature, model and seed. Is this an expected behaviour? What else would I need to set for the same score?

Thank you so much!

**Comment by dauparas** [comment]
Hello!

The network should return deterministic results when the seed is fixed, however the results might differ if using CPU and GPU with the same seed. 

Try running this scoring example: https://github.com/dauparas/ProteinMPNN/blob/main/examples/submit_example_3_score_only.sh
