### ISSUE TITLE
Any way to specify per-residue AA makeups?

### ISSUE THREAD

**Issue by jadolfbr** [dauparas/ProteinMPNN#23]
Sort of like the omit_AAs dictionary, except for individual positions?

**Comment by dauparas** [comment]
yes, check this flag:

argparser.add_argument("--omit_AA_jsonl", type=str, default='', help="Path to a dictionary which specifies which amino acids need to be omited from design at specific chain indices")

e.g. how to make the input: https://github.com/dauparas/ProteinMPNN/blob/main/helper_scripts/other_tools/make_omit_AA.py

**Comment by jadolfbr** [comment]
Awesome! Super helpful!  Thank you!  Would this also work to force specific
positions to be a specific residue? I’ve currently been doing that in
PyRosetta and then passing it along, but I guess if you use this and set AA
weights to 0 vs 1, that could essentially do the trick?

**Comment by dauparas** [comment]
Yes, this should work!
