### ISSUE TITLE
How many sequences to create?

### ISSUE THREAD

**Issue by jadolfbr** [dauparas/ProteinMPNN#24]
What would you recommend for the number of sequences to create for design?  What have you used for production runs?  In the examples, these are usually one or two, but what is generally recommended?

**Comment by dauparas** [comment]
It might depend on the difficulty of the backbone, but I would design 8 sequences per backbone and predict all of them using AlphaFold and then depending on the true LDDTs (or predicted LDDTs) design more sequences if all of them fail to be predicted by AlphaFold confidently.

**Comment by jadolfbr** [comment]
This is extremely helpful.  Thank you Justas!  Is this what was done for
the designs in your paper, basically the number would vary based on
difficulty/fwd folded results? Would you always keep a temp of .1?

**Comment by dauparas** [comment]
I think for most of the designs in the paper only one or couple of sequences were generated because it was easy to get AlphaFold to repredict those structures with those sequences. Yes, a temp of 0.1
