### ISSUE TITLE
Abnormal results

### ISSUE THREAD

**Issue by zdf1122** [dauparas/ProteinMPNN#25]
hello! I found that my result concludes some abnormal amino acid X, I know that it means undefined amino acid. But how did this happen?  When I run the sample, the result is normal. (length of my protein is 1366 aa )
![image](https://user-images.githubusercontent.com/81453850/196085019-c82c61f4-7cde-40be-9087-7421c7277a2a.png)

**Comment by dauparas** [comment]
hello! does the top sequence in the .fasta output file also have those Xs? Could it be that your PDB file has residue jumps in those places?

**Comment by zdf1122** [comment]
> hello! does the top sequence in the .fasta output file also have those Xs? Could it be that your PDB file has residue jumps in those places?
thank you very much !

**Comment by zdf1122** [comment]
> hello! does the top sequence in the .fasta output file also have those Xs? Could it be that your PDB file has residue jumps in those places?

Sorry to bother you again. I wonder if whether the higher the score, global_score and seq_recovery, the better the result.
![image](https://user-images.githubusercontent.com/81453850/196137186-9411b2a9-c9d1-4f24-9b45-26c7809fa9e2.png)

**Comment by dauparas** [comment]
Lower score is better; the score (negative log probability) represents model's uncertainty about the predictions.

**Comment by tony-res** [comment]
I've got a similar output. From what I can tell the original PDB did have residue jumps that were labeled as "-" in pyMol and appear to come out as "X" in the ProteinMPNN output. 

If I wanted to put this sequence into something like AlphaFold or ESM, then would I simply remove the "X"s? Or is there more to it?

e.g. "SEQVXXXKIXM" becomes "SEQVKIM"
