### ISSUE TITLE
How to get the predicted PSSM from structure?

### ISSUE THREAD

**Issue by bzhousd** [dauparas/ProteinMPNN#39]
Dear ProteinMPNN team,

Thank you for building such fantastic method to generate sequences from structure.  I am thinking of getting a PSSM logo from a known structure.  how  can I get the predicted PSSM from a structure?

After I checked the code, it looks like I can use log_probs in this [line](https://github.com/dauparas/ProteinMPNN/blob/main/protein_mpnn_run.py#L249)
, and I also need to run this many times(not sure how big to be converged ) because ProteinMPNN decoder is in random decoding order.  is this correct?

Thank you for your helps in advance

**Comment by dauparas** [comment]
Hello! You can get the PSSM like predicitons using `--unconditional_probs_only 1` flag.
