### ISSUE TITLE
Example of using omit_AA?

### ISSUE THREAD

**Issue by marissadolorfino** [dauparas/ProteinMPNN#41]
I am trying to make single point mutations in a sequence, where I will mutate the single position to all 20 canonical amino acids. I am trying to use design_only_positions and omit_AA, where the first list will include only one position and omit_AA will include all AA except for one. 

I am getting an error regarding omit_AA. Is there an example of how to use omit_AA correctly? Thank you!

**Comment by dauparas** [comment]
Try using the `--omit_AAs` flag; e.g. to exclude everything except alanine use `--omit_AAs "CDEFGHIKLMNPQRSTVWYX"`.

**Comment by marissadolorfino** [comment]
Oh I see, thank you!
