### ISSUE TITLE
scripts to generate PDBID_CHAINID.pt and PDBID.pt   

### ISSUE THREAD

**Issue by johnnyp117** [dauparas/ProteinMPNN#42]
I'd like to use different PDB files to train with, was wondering if there is a script that was used to auto generate the two .pt files mentioned in the issue header. Thanks :).

**Comment by smilenaderi** [comment]
Yes I really need it to? Did you manage to solve it? if so could you please share
thanks very much

**Comment by smilenaderi** [comment]
@decarboxy is there any updates on this? could you please share your codes for preparing data. thanks

**Comment by dauparas** [comment]
I added the script for making PDBID_CHAINID.pt and PDBID.pt: https://github.com/dauparas/ProteinMPNN/blob/main/training/parse_cif_noX.py

**Comment by smilenaderi** [comment]
Thank you so much for sharing!

**Comment by adrienchaton** [comment]
@dauparas thanks a lot for sharing this script!

some related discussion is happening here https://github.com/dauparas/ProteinMPNN/issues/54

currently, if I download a .cif from the PDB website or from the AlphaFold DB, then it gets parsed properly by https://github.com/dauparas/ProteinMPNN/blob/main/training/parse_cif_noX.py#L264

however my data is in .pdb format, if I convert the pdb files to .cif (e.g. using BioPython or PyMol), then parse_mmcif returns empty dict for chains and metadata ...

Any help to prepare training data from .pdb files please? Or what is a compatible conversion to .cif to be able to process my dataset with parse_mmcif?

**Comment by hjistb** [comment]
I think we can use this [function ](https://github.com/dauparas/ProteinMPNN/blob/8907e6671bfbfc92303b5f79c4b5e6ce47cdef57/protein_mpnn_utils.py#L139) to parse the pdb files, and the output could be input to StructureDataset function [here](https://github.com/dauparas/ProteinMPNN/blob/8907e6671bfbfc92303b5f79c4b5e6ce47cdef57/training/training.py#L112).

**Comment by adrienchaton** [comment]
thanks! I will look into that and see if I can customize the training script to load directly from pdb files

**Comment by yaojie-star** [comment]
hi, I was wandering if the input file of parse_cif_noX is some XXXX-assembly1.cif.gz file, but the XXXX.pt is the conclusion of several assemblies(like XXXX-assembly1.cif.gz, XXXX-assembly2.cif.gz,....). how can I use the parse_cif_noX.py to conclude several assemblies into one XXXX.pt, Or am I getting it wrong?Looking forward to your reply @dauparas

**Comment by adrienchaton** [comment]
FYI this repo has implemented and documented some MPNN training on predicted structure pdb files
https://github.com/meilerlab/HyperMPNN/tree/main/mpnn_retrain_docu
