### ISSUE TITLE
Amino acid sequence has too many "A"

### ISSUE THREAD

**Issue by yikehuaili** [dauparas/ProteinMPNN#46]
Dear ProteinMPNN team,
Thank you very much for your great efforts.I want to know why the designed amino acid sequence has a long string of A(i.g. APGDAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)It’s looks unusual.
Thank you for your helps in advance

**Comment by dauparas** [comment]
Hello! This might happen if the model is uncertain about the prediction, or the input backbone is of low quality. You could try adding negative alanine bias.

**Comment by yikehuaili** [comment]
Thank you so much!
