### ISSUE TITLE
Lists of PDB Ids for training and testing

### ISSUE THREAD

**Issue by jadolfbr** [dauparas/ProteinMPNN#5]
Hello,

I am wondering if you have a list of PDB Ids + chains used to train and validate the model.  These would be useful for comparisons to other methods and general benchmarking.  I could not find these listed in the supplemental. 

The list of proteins/chains would be the 25k training clusters, 402 monomer backbones, and then the last set of 690 monomers, 732 homomers (with less than 2000 residues), and 98 heteromers described in the paper.  

Would it be possible to provide these? Thanks!

**Comment by dauparas** [comment]
Hello,

Yes, we are working on making a training/validation/test data for PDB biounits that were used to train ProteinMPNN publicly available. I will let you know when it is ready!

**Comment by jadolfbr** [comment]
Sounds great!  Thanks!

**Comment by Z-MU-Z** [comment]
thanks for the interesting work! I am waiting for this dataset split so long. how is the progress? thank you very much

**Comment by dauparas** [comment]
See valid and test clusters here: https://github.com/dauparas/ProteinMPNN/tree/main/training
