### ISSUE TITLE
Safety of generated sequences

### ISSUE THREAD

**Issue by remybonnav** [dauparas/ProteinMPNN#50]
Hi, I was wondering if there is a way to have a safety filter in silico to be sure that the generated protein sequence with ProteinMPNN is "safe" to use. For example that it is not a toxin, a prion or a cell penetrating peptide?
Do you think a simple blast would be sufficient? 
Are there better tools available (AI based or not) to safely design proteins sequences?

**Comment by dauparas** [comment]
Hello! I am not aware of any specific tools to evaluate the safety of designed protein sequences. A sequence homology search might be a good start.
