### ISSUE TITLE
An example demonstrating PSSM biasing

### ISSUE THREAD

**Issue by GeneMachines** [dauparas/ProteinMPNN#6]
I'm having a little trouble getting the code to run with a PSSM as input. I'm also not 100% sure how PSSM biasing is influenced by the pssm_multi, pssm_threshold, pssm_log_odds_flag, and pssm_bias_flag flags. It would be great to have an example with input files and flag usage when including a PSSM.

Thanks!

**Comment by Gordon5-AI** [comment]
Same questions, this work has been done very well, but the specific meaning of some parameters is not detailed enough. It will be more helpful if you can provide a detailed tutorial later.
Thanks!

**Comment by donglg1309** [comment]
The PSSM flags are confusing based on the current version. A further PSSM help script will be helpful. It seems that the file '/home/swang523/RLcage/capsid/monomersfordesign/8-16-21/pssm_rainity_final_8-16-21_int/build_0.2089_0.98_0.4653_19_2.00_0.005745.pssm' cannot be accessed.

Thanks!

**Comment by dauparas** [comment]
Sorry, I forgot to paste this example here: https://github.com/dauparas/ProteinMPNN/blob/main/examples/submit_example_pssm.sh I hope this helps!
