### ISSUE TITLE
Omit AAs per resiude

### ISSUE THREAD

**Issue by Cookiemaster33** [dauparas/ProteinMPNN#65]
Hi there. 

I was wondering how to use the "--omit_AA_jsonl" flag. It seems that it would be possible to define the omission of certain amino acids per residue. Is there a helper script that can generate the .json file, or do I have to write that myselfe?

Thanks for your help.

Toby

**Comment by dauparas** [comment]
Hi Toby,

Have a look at this helper script: https://github.com/dauparas/ProteinMPNN/blob/main/helper_scripts/other_tools/make_omit_AA.py

**Comment by Cookiemaster33** [comment]
Thank you so much. Should have looked more closely in the scripts folder. Sorry about that. I was able to adapt the script and it runs perfectly fine. When I run my main script however, it gives me the message "omit_AA_jsonl is no NOT loaded". Not sure what I am doing wrong. This is the command I am using:

python ~/Programs/ProteinMPNN/protein_mpnn_run.py \
        --jsonl_path $path_for_parsed_chains \
        --chain_id_jsonl $path_for_assigned_chains \
        --fixed_positions_jsonl $path_for_fixed_positions \
        --out_folder $output_dir \
        --num_seq_per_target 1000 \
        --backbone_noise $noise \
        --sampling_temp $temperature \
        --seed 6 \
        --batch_size 100 \
        --tied_positions_jsonl $path_for_tied_positions
        --omit_AA_jsonl 'inputs/omit_AA.jsonl'

Thanks for your help.

Best
Toby
