### ISSUE TITLE
Error running the examples with jsonl inputs

### ISSUE THREAD

**Issue by lfelipesv** [dauparas/ProteinMPNN#8]
Hello,

We are facing the following error when running the examples that takes jsonl files as inputs. 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1640662/179695242-00941349-f9e6-4738-a816-8a90ef82dc8d.png">

Examples that run the inference on the pdb (with parse_pdbs and StructureDatasetPDB() runs without errors.

Does the code require different formats/parsing for jsonl files? I think currently it is using the parsing from StructureDataset() class

Thank you for the attention!

**Comment by dauparas** [comment]
Hello! 

Try running updated examples. All the required jsonl files are generated by these examples.
