### ISSUE TITLE
Warnings From Example Scripts?

### ISSUE THREAD

**Issue by jamesrgraham** [dauparas/ProteinMPNN#81]
Hello,

What are these warnings ("NOT loaded") that I get when I run the example scripts? The scripts output data, but I'm concerned about the warnings. Also, is the line, `source activate mlfold`, not needed if you already have the Conda env activated?

```
./submit_example_4.sh: line 8: activate: No such file or directory
----------------------------------------
pssm_jsonl is NOT loaded
----------------------------------------
omit_AA_jsonl is NOT loaded
----------------------------------------
bias_AA_jsonl is NOT loaded
----------------------------------------
tied_positions_jsonl is NOT loaded
----------------------------------------
bias by residue dictionary is not loaded, or not provided
----------------------------------------
discarded {'bad_chars': 0, 'too_long': 0, 'bad_seq_length': 0}
----------------------------------------
Number of edges: 48
Training noise level: 0.2A
Generating sequences for: 3HTN
2 sequences of length 429 generated in 3.7705 seconds
Generating sequences for: 4YOW
2 sequences of length 693 generated in 6.6713 seconds

```

Thanks!
james

**Comment by mlnance** [comment]
Hi James,

The warnings can be spooky, but they look fine in this case. The program is just letting you know that you _didn't_ supply any of those files, which is usually fine. I'd only be concerned if, say, you did pass an `omit_AA_jsonl` or something and that same warning came up.

As for the activation part, also should be fine. It looks like your example script ran so your own conda environment should be fine.

I'm not a developer, but essentially don't worry about these warnings!

Hope it helps,
Morgan

**Comment by jamesrgraham** [comment]
Thank you, Morgan! I missed the alerts saying you had commented.
