### ISSUE TITLE
Is there an example on how to score a set of sequences w/ a given backbone (PDB)?

### ISSUE THREAD

**Issue by seyonechithrananda** [dauparas/ProteinMPNN#9]
Hey ProteinMPNN team! Big fan of the work and thank you for the excellent guides that are runnable in Colab.

I'm trying to work through the code base + util file to better understand how to score sequences (the neg. log probability of the sequence given a backbone). My question is, given a set of sequences and a PDB file for my backbone, how can I a) featurize the backbone + b) then compute the neg. log probability for a set of sequences I have wrt to the backbone? 

For reference, here is a similar example of how to do so with [ESM-IF1](https://github.com/facebookresearch/esm/blob/244b2411d7b9e1c70006d7cf231c3750eb81034b/esm/inverse_folding/util.py#L104).

Thanks for your help!

**Comment by dauparas** [comment]
Hey! 

The easiest way would be to create many PDB files with just backbone coordinates and different sequences and then you could run the main script with --score_only 1 option.

Alternatively, I can add a feature to score sequences that are given in .fasta file against the backbone given in .pdb file. This would only work smoothly if sequences in fasta files match in number residues in pdb files for every chain and the chain ordering is given in fasta file.

**Comment by seyonechithrananda** [comment]
> Hey!
> 
> The easiest way would be to create many PDB files with just backbone coordinates and different sequences and then you could run the main script with --score_only 1 option.
> 
> Alternatively, I can add a feature to score sequences that are given in .fasta file against the backbone given in .pdb file. This would only work smoothly if sequences in fasta files match in number residues in pdb files for every chain and the chain ordering is given in fasta file.

Thanks for your helpful reply!! I think the feature to score multiple sequences in a single FASTA against a backbone in a PDB would be incredibly helpful!! (as long as the sequences match the # of residues as you mentioned)

**Comment by dauparas** [comment]
There is a flag called `--path_to_fasta` that allows to do this.
