### ISSUE TITLE
Empty parsed_pdbs.jsonl file from parse_multiple_chains.py helper script?

### ISSUE THREAD

**Issue by emilyrkang** [dauparas/ProteinMPNN#98]
When I execute the parse_multiple_chains.py, it runs without error messages and creates a file in the output location that I expect but the file is empty.

I'm running it on my windows laptop, here is the command I used:
`C:\ProteinMPNN\helper_scripts>py parse_multiple_chains.py --input_path "C:\ProteinMPNN\4rjj.pdb" --output_path "C:\ProteinMPNN\myparsedfilesetc\parsed_pdbs.jsonl"`

The following command works, but I would like to model it as a homooligomer and fix some residues so I think I need to parse it and then make a tied position dictionary.

`py protein_mpnn_run.py
--path_to_model_weights "C:\ProteinMPNN\vanilla_model_weights"
--pdb_path 4rjj.pdb
--pdb_path_chains "A B C D"
--out_folder "C:\ProteinMPNN\myoutputs\4rjj"
--num_seq_per_target 20
--sampling_temp "0.1 0.2 0.3"
--batch_size 1
--omit_AAs='XC'`

Saving the input pdb file and putting the output file in the helper scripts folder doesn't fix it either:
`C:\ProteinMPNN\helper_scripts>py parse_multiple_chains.py --input_path "4rjj.pdb" --output_path "4rjj_parsed_pdbs.jsonl"`

Any help would be much appreciated; thanks in advance!

**Comment by emilyrkang** [comment]
Nevermind, this worked:

`C:\ProteinMPNN\helper_scripts>py parse_multiple_chains.py --input_path "C:\ProteinMPNN" --output_path "C:\ProteinMPNN\myparsedfilesetc\parsed_pdbs.jsonl"`

**Comment by QLQL-s** [comment]
> Nevermind, this worked:
> 
> `C:\ProteinMPNN\helper_scripts>py parse_multiple_chains.py --input_path "C:\ProteinMPNN" --output_path "C:\ProteinMPNN\myparsedfilesetc\parsed_pdbs.jsonl"`

I encountered the same issue as you did, where the output JSONL file was empty when using helper_scripts/parse_multiple_chains.py, but I resolved it by following the methods you provided. However, when I used assign_fixed_chains.py, I encountered the same problem again: the output file was empty. Have you ever encountered such a situation?
I would greatly appreciate any assistance you can provide; thank you beforehand!
